export { default as Drawer } from "./Drawer/Drawer";
export { default as Header } from "./Header/Header"
export { default as CreateClass } from './CreateClass/CreateClass'
export { default as JoinClass } from './JoinClass/JoinClass'
export { default as JoinedClasses } from './JoinedClasses/JoinedClasses'
export { default as Main } from './Main/Main'
export { default as People } from './People/People'
export { default as SignIn } from './SignIn/SignIn'
export { default as SignUp } from './SignUp/SignUp'
export { default as EditProfile } from './EditProfile/EditProfile'
export { default as InvitePeople } from './InvitePeople/InvitePeople'
export { default as CardView } from './CardView/CardView'
export { default as Drag } from './GradeStruct/drag'
